services:
  # Client : Serveur Web Apache
  web-server: 
    build: 
      context: ./client
    container_name: scrapedt-client
    ports:
      - "8081:80" 
    volumes:
      - ./server/ics:/usr/local/apache2/htdocs/api_data/
    restart: unless-stopped
    networks:
      - npm-network

  # Serveur : Script Python
  script-runner:
    build: 
      context: ./server
    container_name: scrapedt-server
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./server/ics:/app/ics
      - ./server:/app
    restart: unless-stopped
    networks:
      - npm-network

networks:
  npm-network:
    external: true